export default {
    SET_FILE: 'SET_FILE',
    SET_TABLE: 'SET_TABLE',
    TOGGLE_VIEW: 'TOGGLE_VIEW',
    PYTHON: {
        SET_EXIST: 'SET_EXIST', 
        SET_PYTHON_INSTALLED: 'SET_PYTHON_INSTALLED', 
        SET_PYTHON_INSTALLING: 'SET_PYTHON_INSTALLING',
    },
    SET_VISUALIZATION: 'SET_VISUALIZATION',
    SET_CURRENT_TAG_TAB: 'SET_CURRENT_TAG_TAB',
    SET_LOADING: 'SET_LOADING',
    CLUSTERGRAMMER: {
        SET_URL: 'SET_URL',
        SET_MULT_VIEW: 'SET_MULT_VIEW',
        SET_HEAT_MAP: 'SET_HEAT_MAP'
    },
    SET_TABLE_ACTIONS: 'SET_TABLE_ACTIONS',
    SET_STITCH_ACTIVE: "SET_STITCH_ACTIVE"
}